# -*- coding: utf-8 -*-
"""AI-Project-1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bwx4zKYCFULFPwNVQ9c5lwvRH2koZkws

#NLP-Sentiment Analysis

##Introduction to the Project

Natural Language Processing (NLP) is a branch of Artificial Intelligence that enables machines to understand and analyze human language.

Sentiment Analysis is a technique used to determine the emotional tone behind a piece of text. It is widely used to classify customer reviews into positive, negative, or neutral sentiments.

In this project, we analyze customer reviews collected from e-commerce platforms to understand customer opinions about a product.

##Objective of EDA

The main objective of Exploratory Data Analysis (EDA) is to:

Understand the structure of the dataset
Identify missing or inconsistent data
Analyze patterns and trends
Extract meaningful insights before model building

EDA helps in making better decisions during preprocessing and modeling stages.

##Import Libraries
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df=pd.read_excel('/content/dataset.xlsx')
df

df.head()

df.tail()

df.info()

df.describe()

df.columns

df.isnull()

df.shape

df.isnull().sum()

"""##Data Cleaning

#####Before analysis, the dataset is cleaned by:

#####Removing missing values using dropna()
#####Ensuring consistency in data types

####This step improves data quality and avoids errors in analysis.
"""

df.dropna(inplace=True)

df.columns

df['review'] = df['title'] + " " + df['body']

"""##Dataset Description

#####The dataset contains customer reviews with the following columns:

#####Title → Short heading of the review
#####Body → Detailed review text
#####Rating → Numerical score given by the customer (1 to 5)

#####A new column called “Review” is created by combining title and body for better analysis.

##Sentiment Creation

#####A new feature called Sentiment is created based on ratings:

#####Ratings 4 and 5 → Positive
#####Rating 3 → Neutral
#####Ratings 1 and 2 → Negative

#####This transformation helps convert numerical ratings into categorical sentiment labels.
"""

def sentiment_label(rating):
    if rating >= 4:
        return "Positive"
    elif rating == 3:
        return "Neutral"
    else:
        return "Negative"

df['sentiment'] = df['rating'].apply(sentiment_label)

df['sentiment'].value_counts()

"""##Univariate Analysis

######Univariate analysis focuses on analyzing a single variable at a time.

####Sentiment Distribution
######Shows how many reviews are positive, negative, and neutral
######Helps understand class imbalance
####Rating Distribution
######Displays the frequency of ratings from 1 to 5
######Indicates overall customer satisfaction
"""

sns.countplot(x='sentiment', data=df)
plt.title("Sentiment Distribution")
plt.show()

sns.countplot(x='rating', data=df)
plt.title("Rating Distribution")
plt.show()

"""##Text Analysis
####Review Length Analysis
######Measures the length of each review
######Helps understand whether customers give detailed feedback
####Histogram Plot
######Shows distribution of review lengths
######Identifies whether most reviews are short or long
"""

df['review_length'] = df['review'].apply(len)

sns.histplot(df['review_length'], kde=True)
plt.title("Review Length Distribution")
plt.show()

"""##Bivariate Analysis

######Bivariate analysis studies the relationship between two variables.

####Sentiment vs Review Length
######Uses boxplot to compare review lengths across sentiments
######Helps identify patterns (e.g., negative reviews are often longer)
"""

sns.boxplot(x='sentiment', y='review_length', data=df)
plt.title("Sentiment vs Review Length")
plt.show()

"""##Word Frequency Analysis
######Extracts most commonly used words in reviews
######Helps identify frequently discussed terms by customers

"""

from collections import Counter

all_words = " ".join(df['review']).split()
common_words = Counter(all_words).most_common(10)
print(common_words)

"""##WordCloud Visualization

######WordCloud is used to visually represent the most frequent words.

######Larger words indicate higher frequency
######Provides quick understanding of common themes in reviews

######Separate WordClouds can be created for:

######Positive reviews
######Negative reviews
"""

from wordcloud import WordCloud

wordcloud = WordCloud(width=800, height=400).generate(" ".join(df['review']))

plt.imshow(wordcloud)
plt.axis('off')
plt.title("Word Cloud")
plt.show()

"""##Text Preprocessing (EDA Support Step)

Text data is cleaned by:

Converting to lowercase
Removing special characters
Removing stopwords (e.g., “the”, “is”)

This improves clarity of textual analysis and visualization.

##Key Insights

From the EDA, we observed that:

Majority of reviews are positive
Higher ratings (4 and 5) are more frequent
Negative reviews tend to be longer and more detailed
Frequently used words reflect customer opinions about product quality

##Conclusion on (EDA)
EDA provides a clear understanding of customer review patterns and sentiment distribution. It prepares the dataset for further processing and model building.

The insights gained during this phase are crucial for building an accurate sentiment analysis model.

#Text Preprocessing

Before applying machine learning algorithms, text data must be cleaned and standardized.

#Objective

To remove unnecessary words, symbols, and noise from textual data.
"""

import re
import nltk
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer

"""Stopwords are commonly used words such as:

######the
######is
######and
######was

These words do not contribute much to sentiment prediction.
"""

nltk.download('stopwords')

stemmer = PorterStemmer()

"""Stemming converts words into root forms.

Examples:

######running → run
######loved → love

This reduces vocabulary size.
"""

def clean_text(text):

    text = text.lower()

    text = re.sub(r'[^a-zA-Z]', ' ', text)

    words = text.split()

    words = [stemmer.stem(word) for word in words
             if word not in stopwords.words('english')]

    return " ".join(words)

"""This function performs:

######Lowercase conversion
######Removal of special characters
######Stopword removal
######Stemming

This improves text quality for machine learning models.

A new column clean_review is created containing cleaned review text.
"""

df['clean_review'] = df['review'].apply(clean_text)

"""#Feature Extraction

Machine learning models cannot understand text directly.

Text must be converted into numerical vectors.
#TF-IDF Vectorization

TF-IDF converts text into numerical features based on word importance.
"""

from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer(max_features=5000)

X = tfidf.fit_transform(df['clean_review']).toarray()

"""TF-IDF stands for:

######Term Frequency
######Inverse Document Frequency

It assigns higher importance to meaningful words.

Example:

######common words → lower importance
######unique words → higher importance

#Target Variable
The target variable contains sentiment labels:

######Positive
######Negative
######Neutral
"""

y = df['sentiment']

"""#Encoding Target Variable

Machine learning models require numerical labels.
Label Encoding converts:

######Positive → 2
######Neutral → 1
######Negative → 0

(Values may vary)
"""

from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

y = le.fit_transform(y)

"""#Train-Test Split
Dataset is divided into:

######Training data
######Testing data

This helps evaluate model performance on unseen reviews.
"""

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42
)

"""#Model Building
#Naive Bayes Classifier

Naive Bayes is one of the best algorithms for NLP classification.
######Naive Bayes:

Works efficiently on text data
Handles word frequency well
Fast and lightweight

It is widely used in sentiment analysis and spam detection.

"""

from sklearn.naive_bayes import MultinomialNB

model = MultinomialNB()

model.fit(X_train, y_train)

"""#Predictions
The trained model predicts sentiment labels for unseen reviews.
"""

y_pred = model.predict(X_test)

"""#Model Evaluation
#Accuracy Score
Accuracy measures the percentage of correctly classified reviews.

Accuracy=
TP+TN+FP+FN/
TP+TN
	​


Higher accuracy indicates better model performance.
"""

from sklearn.metrics import accuracy_score

accuracy_score(y_test, y_pred)

"""#Confusion Matrix
Confusion matrix helps identify:

######Correct predictions
######Incorrect predictions
######Misclassified sentiments
"""

from sklearn.metrics import confusion_matrix

confusion_matrix(y_test, y_pred)

"""#Classification Report
Classification report includes:

######Precision
######Recall
F1-score

These metrics provide detailed evaluation of sentiment classification performance.
"""

from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred))

"""#Logistic Regression
Logistic Regression is another powerful classification algorithm used for sentiment prediction.

It often performs well with TF-IDF features.
"""

from sklearn.linear_model import LogisticRegression

lr = LogisticRegression()

lr.fit(X_train, y_train)

y_pred_lr = lr.predict(X_test)

accuracy_score(y_test, y_pred_lr)

"""#Save the Model
The trained model and TF-IDF vectorizer are saved for deployment.

This avoids retraining every time.
"""

import pickle

pickle.dump(model, open('sentiment_model.pkl', 'wb'))
pickle.dump(tfidf, open('tfidf_vectorizer.pkl', 'wb'))

"""#Conclusion for Text Preprocessing

Text preprocessing was successfully performed to clean and prepare the customer review data for machine learning analysis.

Several preprocessing techniques such as lowercase conversion, removal of special characters, stopword removal, and stemming were applied to improve the quality and consistency of the textual data.

The cleaned reviews were then transformed into numerical representations using TF-IDF vectorization, enabling machine learning algorithms to understand and process the text effectively.

Overall, preprocessing helped reduce noise in the dataset, improve feature quality, and prepare the data for accurate sentiment classification.

#Conclusion for Model Building and Evaluation
Machine learning models were successfully built and evaluated for sentiment classification using customer review data.
Algorithms such as Naive Bayes and Logistic Regression were implemented to predict whether a review expressed positive, negative, or neutral sentiment.
The models were evaluated using performance metrics such as accuracy score, confusion matrix, precision, recall, and F1-score to measure prediction effectiveness.
Among the implemented models, Naive Bayes performed efficiently for text classification due to its ability to handle word frequency-based features effectively.
Finally, the trained model and TF-IDF vectorizer were saved for deployment, enabling real-time sentiment prediction through web applications such as Streamlit or Flask.
"""

pip install streamlit

